---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - bundlemetadata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - bundlemetadata/finalizers
  verbs:
  - update
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - bundlemetadata/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - catalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - catalogs/finalizers
  verbs:
  - update
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - catalogs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - packages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - packages/finalizers
  verbs:
  - update
- apiGroups:
  - catalogd.operatorframework.io
  resources:
  - packages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
